[PR] Post Entity PullReuset
Dokkabei97/dastargram pull request #21
Opened 2023-06-16 18:30 UTC by yoonyoon98

## 요약
게시물 entity

## 작업 내용
- 게시물 entity 생성
- 게시물 entity 테스트 코드 생성 

## 이슈 번호
#7

2023-06-17 04:39 UTC, Dokkabei97 requested changes
일부 코드에서 Java 처럼 `;`가 들어가 있는게 있네요 해당 부분 수정 부탁드립니다

2023-06-17 04:39 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/post/domain/Post.kt
> +        @Column(name = "post_content")
```java
@Column(name="post_content", columnDefinition = "text")
```
으로 수정해서 RDBMS에서 타입을 명시해주는게 좋을꺼 같습니다.

2023-06-17 04:39 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/post/domain/Post.kt
> +        @Column(name = "postImages", columnDefinition = "json")
```java
@Column(name = "postImages", columnDefinition = "json")
```

아직 DB 테이블 정의가 안되었지만 코드의 통일성을 위해
name 부분 카멜케이스에서 스네이크 케이스로 변경 부탁드립니다

2023-06-17 04:39 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/post/domain/Post.kt
> +    }
게시글 수정이나 삭제 기능은 추후에 만들 예정인가요?

2023-06-17 04:39 UTC, Dokkabei97 commented on src/test/kotlin/com/d1t/dastargram/domain/post/PostTest.kt
> +                    Post.create(member, "test", emptyList());
```kotlin
Post.create(member, "test", emptyList());
```

해당 테스트는 사진이 10개 이상 들어가는 테스트인데 `postImages`가 아닌 emptyList()가 들어가 있네요

2023-06-19 10:29 UTC, yoonyoon98 commented on src/main/kotlin/com/d1t/dastargram/domain/post/domain/Post.kt
> +        @Column(name = "post_content")
수정했습니다.

2023-06-19 10:29 UTC, yoonyoon98 commented on src/main/kotlin/com/d1t/dastargram/domain/post/domain/Post.kt
> +        @Column(name = "postImages", columnDefinition = "json")
수정했습니다.

2023-06-19 10:30 UTC, yoonyoon98 commented on src/test/kotlin/com/d1t/dastargram/domain/post/PostTest.kt
> +                    Post.create(member, "test", emptyList());
수정했습니다.

2023-06-19 10:44 UTC, merged