Feature/comment
Dokkabei97/dastargram pull request #31
Opened 2023-07-24 11:23 UTC by Yisak5

## 요약
댓글 서비스 개발
## 작업 내용
- 댓글 추가 구현
- 댓글 수정 구현
- 댓글 삭제 구현
- 테스트 코드 미완성 (수정 예정)

## 이슈 번호
#29

2023-07-24 11:45 UTC, Yisak5 commented
Build 실패 원인은 jwt Token 문제로 
![image](https://github.com/Dokkabei97/dastargram/assets/92911101/f8f724ff-04ed-4ff8-8c7e-4acae551def6)
와 동일한 문제로 파악됨

2023-07-24 22:49 UTC, Dokkabei97 requested changes
**23.07.25** 기준 `develop` 브랜치 최신화 진행되어 로컬 및 CI환경에 build시 test에서 에러가 나던 이슈가 해결되었습니다.

develop 브랜치 머지하여 최신화 하고 코드 변경하여서 다시 pr요청 부탁드립니다.

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/Comment.kt
>      @JoinColumn(name = "member_id")
테크챌린지 설명 했듯 Member와 연관관계를 끊고
```kotlin
var memberId: Long
```
으로 변경하는거 어떨까요?

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/CommentServiceImpl.kt
> +class CommentServiceImpl(val memberReader: MemberReader, val postReader: PostReader, val commentStore: CommentStore) : CommentService {
```kotlin
class CommentServiceImpl(val memberReader: MemberReader, val postReader: PostReader, val commentStore: CommentStore)
```
을 가독성있게 바꾸면 좋을꺼 같습니다. 한번 `MemberServiceImpl`을 참고해 보세요~

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/CommentServiceImpl.kt
> +class CommentServiceImpl(val memberReader: MemberReader, val postReader: PostReader, val commentReader: CommentReader, val commentStore: CommentStore) : CommentService {
가독성 개선이 필요할꺼 같습니다.

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/CommentServiceImpl.kt
> +        val member = memberReader.getMemberById(deleteRequest.memberId)
```kotlin
val mebmer = memberReader.getMemberById(memberId)
val comment = commentReader.getCommentById(id)
```
해당 코드가 공통적으로 들어가고 있는데 어떻게 하면 해당 코드의 중복을 최소화 가능할까요?

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/dto/CommentRequest.kt
>  class CommentRequest {
`CommentRequest`는 DTO인거 같습니다.

구현은 내부 `data class`로 되어 있는데 네임 컨벤션이 카멜케이스를 사용한 이유가 있을까요?

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/CommentServiceImpl.kt
> +        val member = memberReader.getMemberById(deleteRequest.memberId)
```kotlin
 if (member.id != comment.member.id) {
            throw IllegalArgumentException("요청 id와 댓글 게시자의 id가 일치하지 않습니다.")
}
```
1. 해당 코드 또한 중복이 있는데 중복을 피하는 방법이 있을까요?
2. if문 말고 다른 함수를 사용해서 쉽게 `Exception` 처리를 하는 방법이 있을까요?

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/infrastructure/CommentReaderImpl.kt
> +    override fun getCommentById(commentId: Long): Comment = commentRepository.findByIdOrNull(commentId)
```kotlin
 override fun getCommentById(commentId: Long): Comment = commentRepository.findByIdOrNull(commentId)
        ?: throw EntityNotFoundException("존재하지 않는 댓글입니다.")
```

해당 코드에서 ?: 는 무슨 함수이며 어떤 동작을 할까요??

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/dto/CommentRequest.kt
>  class CommentRequest {
해당 DTO에서도 일부 코드가 중복이 되고 있는데 줄이는 방법이 있을까요?

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/dto/CommentResponse.kt
> +data class CommentResponse (
`likeCount`와 `content`만 반환 하는 이유가 있을까요?

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/api/CommentController.kt
> +    fun remove(@RequestBody @Validated deleteRequest: CommentRequest.deleteRequest): CommonResponse<Nothing?> {
1. `Noting`과 `Unit`의 차이는 무엇일까요?
2. `Noting`을 선택한 이유는 무엇인가요?

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/Comment.kt
>      @Column(name = "comment_like_count", columnDefinition = "int default 0")
`@Column(name = "comment_like_count", columnDefinition = "int default 0")`

`int default 0`을 준 이유를 알 수 있을까요?

2023-07-24 22:49 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/dto/CommentRequest.kt
DTO가 단순 데이터를 전송하는 객체라고 쉽게 생각되어도 코드에 따라 유지 보수 및 사용성이 바뀐다고 생각합니다.

2023-08-07 10:47 UTC, Yisak5 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/Comment.kt
>      @Column(name = "comment_like_count", columnDefinition = "int default 0")
객체에서 초기 값 지정하고 있어서 굳이 필요 없겠네요. 
수정 하겠습니다.

2023-08-07 10:53 UTC, Yisak5 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/api/CommentController.kt
> +    fun remove(@RequestBody @Validated deleteRequest: CommentRequest.deleteRequest): CommonResponse<Nothing?> {
Unit은 아무런 값을 반환하지 않는 반환 타입이고, Nothing은 값을 반환하지 않는다는 반환 타입이네요.. Unit 으로 수정 했습니다

2023-08-07 10:55 UTC, Yisak5 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/infrastructure/CommentReaderImpl.kt
> +    override fun getCommentById(commentId: Long): Comment = commentRepository.findByIdOrNull(commentId)
null 값 처리입니다. null인 경우 우측의 EntityNotFoundException을 발생시킵니다.

2023-08-07 11:13 UTC, Yisak5 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/dto/CommentResponse.kt
> +data class CommentResponse (
id 도 반환 해줘야 하겠네요. 수정했습니다.

2023-08-07 11:13 UTC, Yisak5 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/CommentServiceImpl.kt
> +        val member = memberReader.getMemberById(deleteRequest.memberId)
if -> check로 수정 했습니다

2023-08-07 11:16 UTC, Yisak5 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/dto/CommentRequest.kt
>  class CommentRequest {
대문자로 수정했습니다.

2023-08-07 11:19 UTC, Yisak5 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/CommentServiceImpl.kt
> +class CommentServiceImpl(val memberReader: MemberReader, val postReader: PostReader, val commentStore: CommentStore) : CommentService {
가독성 수정했습니다.

2023-08-07 11:20 UTC, Yisak5 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/Comment.kt
>      @JoinColumn(name = "member_id")
post, member 연관관계 수정했습니다.

2023-08-07 11:26 UTC, Yisak5 commented
리뷰 해 주신 부분 수정해서 다시 PR 했습니다.

2023-08-07 12:37 UTC, Dokkabei97 commented on src/main/kotlin/com/d1t/dastargram/domain/comment/domain/Comment.kt
> +    @Column(name = "post_id")
Post는 댓글과 연관 관계가 긴밀해서 Post는 연관 관계 유지하는게 좋습니다.

2023-08-07 12:38 UTC, Dokkabei97 commented
좀 더 자세한 리뷰는 추후에 다 같이 진행하겠습니다.

2023-08-07 12:38 UTC, merged